name: Scheduled Node.js CI

on:
  schedule:
    # 每天 UTC 时间 18:00 运行
    - cron: "0 18 * * *"
  workflow_dispatch: # 添加这行以允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # 设置作业超时时间为20分钟

    strategy:
      matrix:
        node-version: [20.x] # 选择你需要的 Node.js 版本
    env:
      # 在作业级别设置环境变量
      USERNAMES: ${{ secrets.USERNAMES }}
      PASSWORDS: ${{ secrets.PASSWORDS }}

    steps:
      - uses: actions/checkout@v3 # 检出你的仓库
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install # 安装 package.json 中的依赖项
      - name: Run a script
        run: node pteer.js # 替换为你想运行的脚本的实际名称
